/**
 * Personal Information Hub
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['js/pih/client/ApiClient', 'js/pih/client/model/ApiError', 'js/pih/client/model/Category', 'js/pih/client/model/FoundDoc', 'js/pih/client/model/IndexedItem', 'js/pih/client/model/LoginRequest', 'js/pih/client/model/MatchedDetailInformation', 'js/pih/client/model/PlainText', 'js/pih/client/model/RegistrationRequest', 'js/pih/client/model/SearchResult', 'js/pih/client/model/Tag', 'js/pih/client/model/UpdatePasswordRequest', 'js/pih/client/model/UserInfo', 'js/pih/client/model/UserSetting', 'js/pih/client/api/AuthApi', 'js/pih/client/api/DataApi', 'js/pih/client/api/UserApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/ApiError'), require('./model/Category'), require('./model/FoundDoc'), require('./model/IndexedItem'), require('./model/LoginRequest'), require('./model/MatchedDetailInformation'), require('./model/PlainText'), require('./model/RegistrationRequest'), require('./model/SearchResult'), require('./model/Tag'), require('./model/UpdatePasswordRequest'), require('./model/UserInfo'), require('./model/UserSetting'), require('./api/AuthApi'), require('./api/DataApi'), require('./api/UserApi'));
  }
}(function(ApiClient, ApiError, Category, FoundDoc, IndexedItem, LoginRequest, MatchedDetailInformation, PlainText, RegistrationRequest, SearchResult, Tag, UpdatePasswordRequest, UserInfo, UserSetting, AuthApi, DataApi, UserApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var PersonalInformationHub = require('js/pih/client/index'); // See note below*.
   * var xxxSvc = new PersonalInformationHub.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new PersonalInformationHub.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['js/pih/client/index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new PersonalInformationHub.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new PersonalInformationHub.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module js/pih/client/index
   * @version 0.0.1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:js/pih/client/ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ApiError model constructor.
     * @property {module:js/pih/client/model/ApiError}
     */
    ApiError: ApiError,
    /**
     * The Category model constructor.
     * @property {module:js/pih/client/model/Category}
     */
    Category: Category,
    /**
     * The FoundDoc model constructor.
     * @property {module:js/pih/client/model/FoundDoc}
     */
    FoundDoc: FoundDoc,
    /**
     * The IndexedItem model constructor.
     * @property {module:js/pih/client/model/IndexedItem}
     */
    IndexedItem: IndexedItem,
    /**
     * The LoginRequest model constructor.
     * @property {module:js/pih/client/model/LoginRequest}
     */
    LoginRequest: LoginRequest,
    /**
     * The MatchedDetailInformation model constructor.
     * @property {module:js/pih/client/model/MatchedDetailInformation}
     */
    MatchedDetailInformation: MatchedDetailInformation,
    /**
     * The PlainText model constructor.
     * @property {module:js/pih/client/model/PlainText}
     */
    PlainText: PlainText,
    /**
     * The RegistrationRequest model constructor.
     * @property {module:js/pih/client/model/RegistrationRequest}
     */
    RegistrationRequest: RegistrationRequest,
    /**
     * The SearchResult model constructor.
     * @property {module:js/pih/client/model/SearchResult}
     */
    SearchResult: SearchResult,
    /**
     * The Tag model constructor.
     * @property {module:js/pih/client/model/Tag}
     */
    Tag: Tag,
    /**
     * The UpdatePasswordRequest model constructor.
     * @property {module:js/pih/client/model/UpdatePasswordRequest}
     */
    UpdatePasswordRequest: UpdatePasswordRequest,
    /**
     * The UserInfo model constructor.
     * @property {module:js/pih/client/model/UserInfo}
     */
    UserInfo: UserInfo,
    /**
     * The UserSetting model constructor.
     * @property {module:js/pih/client/model/UserSetting}
     */
    UserSetting: UserSetting,
    /**
     * The AuthApi service constructor.
     * @property {module:js/pih/client/api/AuthApi}
     */
    AuthApi: AuthApi,
    /**
     * The DataApi service constructor.
     * @property {module:js/pih/client/api/DataApi}
     */
    DataApi: DataApi,
    /**
     * The UserApi service constructor.
     * @property {module:js/pih/client/api/UserApi}
     */
    UserApi: UserApi
  };

  return exports;
}));
