export const PAGES_MAP = {
  alarm: '/pages/alarm',
  organization: '/pages/authority/organization',
  rule: '/pages/rule',
  role: '/pages/authority/role',
  group: '/pages/group',
  log: '/pages/log',
  'city-op': '/pages/city-op',
  'city-app': '/pages/city-app',
  datasources: '/pages/dashboard/datasources',
  authorization: '/pages/authority/authorization',
  'slice-list': '/pages/dashboard/slice-list',
  'device-registration': '/pages/device/device-registration',
  'dashboard-list': '/pages/dashboard/dashboard-list',
  'asset-explorer': '/pages/asset/asset-explorer',
  'user-explorer': '/pages/authority/user-explorer',
  'device-explorer': '/pages/device/device-explorer',
  'asset-template-explorer': '/pages/asset/asset-template-explorer',
  'dashboard-explorer': '/pages/dashboard/dashboard-explorer',
  'device-control': '/pages/device/device-explorer',
  'custom-field': '/pages/system-setting/custom-field',
  'app-config': '/pages/system-setting/app-config',
  'map-config': '/pages/system-setting/map-config',
  'device-resources': '/pages/system-setting/device-resources',
  'device-keysConfiguration': '/pages/system-setting/device-keysConfiguration',
  'batch-command': '/pages/task/batch-command',
  'power-grid-organization': '/pages/task/power-grid-organization',
  'power-grid-group': '/pages/task/power-grid-group',
  'na-register': '/pages/na-register',
  common: [
    '/pages/dashboard/empty-placeholder',
    '/pages/authority/user/personal',
    '/pages/components-sample',
    '/pages/webgis',
  ],
};

