/**
 * Personal Information Hub
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['js/pih/client/ApiClient', 'js/pih/client/model/Category', 'js/pih/client/model/MatchedDetailInformation', 'js/pih/client/model/Tag'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Category'), require('./MatchedDetailInformation'), require('./Tag'));
  } else {
    // Browser globals (root is window)
    if (!root.PersonalInformationHub) {
      root.PersonalInformationHub = {};
    }
    root.PersonalInformationHub.FoundDoc = factory(root.PersonalInformationHub.ApiClient, root.PersonalInformationHub.Category, root.PersonalInformationHub.MatchedDetailInformation, root.PersonalInformationHub.Tag);
  }
}(this, function(ApiClient, Category, MatchedDetailInformation, Tag) {
  'use strict';




  /**
   * The FoundDoc model module.
   * @module js/pih/client/model/FoundDoc
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>FoundDoc</code>.
   * @alias module:js/pih/client/model/FoundDoc
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>FoundDoc</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:js/pih/client/model/FoundDoc} obj Optional instance to populate.
   * @return {module:js/pih/client/model/FoundDoc} The populated <code>FoundDoc</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('comments')) {
        obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
      }
      if (data.hasOwnProperty('link')) {
        obj['link'] = ApiClient.convertToType(data['link'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('size')) {
        obj['size'] = ApiClient.convertToType(data['size'], 'Integer');
      }
      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'Integer');
      }
      if (data.hasOwnProperty('tags')) {
        obj['tags'] = ApiClient.convertToType(data['tags'], [Tag]);
      }
      if (data.hasOwnProperty('categories')) {
        obj['categories'] = ApiClient.convertToType(data['categories'], [Category]);
      }
      if (data.hasOwnProperty('hits')) {
        obj['hits'] = ApiClient.convertToType(data['hits'], 'Integer');
      }
      if (data.hasOwnProperty('more')) {
        obj['more'] = ApiClient.convertToType(data['more'], 'Boolean');
      }
      if (data.hasOwnProperty('fields')) {
        obj['fields'] = ApiClient.convertToType(data['fields'], [MatchedDetailInformation]);
      }
    }
    return obj;
  }

  /**
   * Doc id
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Title
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * Comments
   * @member {String} comments
   */
  exports.prototype['comments'] = undefined;
  /**
   * Link
   * @member {String} link
   */
  exports.prototype['link'] = undefined;
  /**
   * Type
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * Size
   * @member {Integer} size
   */
  exports.prototype['size'] = undefined;
  /**
   * Date
   * @member {Integer} date
   */
  exports.prototype['date'] = undefined;
  /**
   * Tags
   * @member {Array.<module:js/pih/client/model/Tag>} tags
   */
  exports.prototype['tags'] = undefined;
  /**
   * Categories
   * @member {Array.<module:js/pih/client/model/Category>} categories
   */
  exports.prototype['categories'] = undefined;
  /**
   * Hits in Doc
   * @member {Integer} hits
   */
  exports.prototype['hits'] = undefined;
  /**
   * Whether actual hits greater than hits shown
   * @member {Boolean} more
   * @default false
   */
  exports.prototype['more'] = false;
  /**
   * Matched Fields
   * @member {Array.<module:js/pih/client/model/MatchedDetailInformation>} fields
   */
  exports.prototype['fields'] = undefined;



  return exports;
}));


